package org.example.nihongobackend.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Layer 3: Shared AI Vocabulary Cache
 * - Global cache: ALL users benefit from AI lookups
 * - Grows over time: ~20k unique queries asymptote
 * - 99% cache hit rate after 6 months
 * - Cost savings: 99% reduction in AI API calls
 */
@Entity
@Table(name = "ai_vocab_cache")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class AiVocabCache {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    /**
     * Japanese word (UNIQUE - global cache key)
     */
    @Column(nullable = false, unique = true, length = 500)
    private String word;

    /**
     * Reading in hiragana/katakana
     */
    @Column(length = 500)
    private String reading;

    /**
     * Vietnamese meaning generated by AI
     */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String meaningVi;

    /**
     * Source: 'ai' (from AI service) or 'admin_generated' (manually created)
     */
    @Column(length = 20)
    private String source = "ai";

    /**
     * AI model used: 'gemini-1.5-flash', 'deepseek-chat', etc.
     */
    @Column(length = 50)
    private String model;

    /**
     * Admin verified this translation?
     */
    @Column(nullable = false)
    private Boolean isVerified = false;

    /**
     * Admin user who verified (if applicable)
     */
    @Column
    private UUID verifiedBy;

    /**
     * How many times this word was queried (cache hit count)
     */
    @Column(nullable = false)
    private Integer queryCount = 1;

    /**
     * First time this word was queried
     */
    @Column(nullable = false)
    private LocalDateTime firstQueried;

    /**
     * Last time this word was queried
     */
    @Column(nullable = false)
    private LocalDateTime lastQueried;

    /**
     * How many users reported issues with this translation
     */
    @Column(nullable = false)
    private Integer reportCount = 0;

    /**
     * When this entry was created
     */
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * When this entry was last updated
     */
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    void onCreate() {
        this.createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
        this.firstQueried = LocalDateTime.now();
        this.lastQueried = LocalDateTime.now();
        if (this.queryCount == null) {
            this.queryCount = 1;
        }
        if (this.reportCount == null) {
            this.reportCount = 0;
        }
        if (this.isVerified == null) {
            this.isVerified = false;
        }
        if (this.source == null) {
            this.source = "ai";
        }
    }

    @PreUpdate
    void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    /**
     * Increment query count when cache hit occurs
     */
    public void incrementQueryCount() {
        this.queryCount++;
        this.lastQueried = LocalDateTime.now();
    }

    /**
     * Increment report count when user reports issue
     */
    public void incrementReportCount() {
        this.reportCount++;
    }
}
